
<?php 

$musicData = [
	[
		"id" => 1,
		"year" => 2011,
		"genre" => "Rock",
		"listened" => 12,
		"album" => "Megalithic Symphony",
		"artist" => "Awolnation",
		"song" => "Sail",
		"picture" => "", 
	],
	[
		"id" => 2,
		"year" => 2014,
		"genre" => "Pop",
		"listened" => 21,
		"album" => "1000 Forms of Fear",
		"artist" => "Sia",
		"song" => "Elastic Heart",
		"picture" => "",
	],
	[
		"id" => 3,
		"year" => 2018,
		"genre" => "Latin",
		"listened" => 145,
		"album" => "Real Hasta la Muerte",
		"artist" => "Anuel AA",
		"song" => "Quiere Beber",
		"picture" => "",
	],
	[
		"id" => 4,
		"year" => 2014,
		"genre" => "EDM",
		"listened" => 104,
		"album" => "Motion",
		"artist" => "Calvin Harris",
		"song" => "Summer",
		"picture" => "",
	],
	[
		"id" => 5,
		"year" => 2018,
		"genre" => "Hip-Hop",
		"listened" => 80,
		"album" => "Scorpion",
		"artist" => "Drake",
		"song" => "God's Plan",
		"picture" => "",
	],
	[
		"id" => 6,
		"year" => 2001,
		"genre" => "Rock",
		"listened" => 99,
		"album" => "Toxicity",
		"artist" => "System Of A Down",
		"song" => "Chop Suey!",
		"picture" => "",
	],
	[
		"id" => 7,
		"year" => 2007,
		"genre" => "Pop",
		"listened" => 56,
		"album" => "Blackout",
		"artist" => "Britney Spears",
		"song" => "Gimme More",
		"picture" => "",
	],
	[
		"id" => 8,
		"year" => 2004,
		"genre" => "Latin",
		"listened" => 78,
		"album" => "Barrio Fino",
		"artist" => "Daddy Yankee",
		"song" => "Gasolina",
		"picture" => "",
	],
	[
		"id" => 9,
		"year" => 2001,
		"genre" => "EDM",
		"listened" => 285,
		"album" => "Discovery",
		"artist" => "Daft Punk",
		"song" => "One More Time",
		"picture" => "",
	],
	[
		"id" => 10,
		"year" => 2008,
		"genre" => "Hip-Hop",
		"listened" => 112,
		"album" => "Tha Carter III",
		"artist" => "Lil Wayne",
		"song" => "A Milli",
		"picture" => "",
	],
	[
		"id" => 11,
		"year" => 1990,
		"genre" => "Rock",
		"listened" => 193,
		"album" => "The Razor Edge",
		"artist" => "AC/DC",
		"song" => "Thunderstruck",
		"picture" => "",
	],
	[
		"id" => 12,
		"year" => 1996,
		"genre" => "Pop",
		"listened" => 82,
		"album" => "Backstreet Boys",
		"artist" => "Backstreet Boys",
		"song" => "Everybody",
		"picture" => "",
	],
	[
		"id" => 13,
		"year" => 1994,
		"genre" => "Latin",
		"listened" => 134,
		"album" => "Amor Prohibido",
		"artist" => "Selena",
		"song" => "Bidi Bidi Bom Bom",
		"picture" => "",
	],
	[
		"id" => 14,
		"year" => 1999,
		"genre" => "EDM",
		"listened" => 45,
		"album" => "Sandstorm",
		"artist" => "Darude",
		"song" => "Sandstorm",
		"picture" => "",
	],
	[
		"id" => 15,
		"year" => 1999,
		"genre" => "Hip-Hop",
		"listened" => 49,
		"album" => "The Slim Shady",
		"artist" => "Eminem",
		"song" => "My Name is",
		"picture" => "",
	],
	[
		"id" => 16,
		"year" => 1987,
		"genre" => "Rock",
		"listened" => 199,
		"album" => "Appetite For Destruction",
		"artist" => "Guns N' Roses",
		"song" => "Welcome To The Jungle",
		"picture" => "",
	],
	[
		"id" => 17,
		"year" => 1982,
		"genre" => "Pop",
		"listened" => 101,
		"album" => "Thriller",
		"artist" => "Michael Jackson",
		"song" => "Thriller",
		"picture" => "",
	],
	[
		"id" => 18,
		"year" => 1985,
		"genre" => "Latin",
		"listened" => 26,
		"album" => "Sergio El Bailador",
		"artist" => "Bronco",
		"song" => "Sergio el Bailador",
		"picture" => "",
	],
	[
		"id" => 19,
		"year" => 1983,
		"genre" => "EDM",
		"listened" => 33,
		"album" => "Sweet Dreams(Are Made Of This)",
		"artist" => "Eurythmics",
		"song" => "Sweet Dreams(Are made of This)",
		"picture" => "",
	],
	[
		"id" => 20,
		"year" => 1986,
		"genre" => "Hip-Hop",
		"listened" => 42,
		"album" => "Raising Hell",
		"artist" => "Run-D.M.C.",
		"song" => "Peter Piper",
		"picture" => "",
	],
	[
		"id" => 21,
		"year" => 1975,
		"genre" => "Rock",
		"listened" => 128,
		"album" => "A Night At The Opera",
		"artist" => "Queen",
		"song" => "Bohemian Rahpsody",
		"picture" => "",
	],
	[
		"id" => 22,
		"year" => 1976,
		"genre" => "Pop",
		"listened" => 24,
		"album" => "Arrival",
		"artist" => "ABBA",
		"song" => "Dancing Queen",
		"picture" => "",
	],
	[
		"id" => 23,
		"year" => 1972,
		"genre" => "Latin",
		"listened" => 185,
		"album" => "El Idolo De Mexico",
		"artist" => "Vicente Fernandez",
		"song" => "El Rey",
		"picture" => "",
	],
	[
		"id" => 24,
		"year" => 1978,
		"genre" => "EDM",
		"listened" => 11,
		"album" => "YMCA",
		"artist" => "Village People",
		"song" => "YMCA",
		"picture" => "",
	],
	[
		"id" => 25,
		"year" => 1980,
		"genre" => "Hip-Hop",
		"listened" => 60,
		"album" => "The Sugarhill Gang",
		"artist" => "The Sugarhill Gang",
		"song" => "Rapper's Delight",
		"picture" => "",
	],
];